export const REGISTER_REQUEST_LOADING = 'REGISTER_REQUEST_LOADING';
export const REGISTER_REQUEST_SUCCESS = 'REGISTER_REQUEST_SUCCESS';
export const REGISTER_REQUEST_FAILED = 'REGISTER_REQUEST_FAILED';
export const REGISTERED_FALSE = 'REGISTERED_FALSE';