export const GET_CHALLENGES_TYPE_STATE_FAILED = 'GET_CHALLENGES_TYPE_STATE_FAILED';
export const GET_CHALLENGES_TYPE_STATE_SUCCESS = 'GET_CHALLENGES_TYPE_STATE_SUCCESS';
export const GET_CHALLENGES_TYPE_STATE_LOADING = 'GET_CHALLENGES_TYPE_STATE_LOADING';
export const ADD_CHALLENGE_TYPE_LOADING = 'ADD_CHALLENGE_TYPE_LOADING';
export const ADD_CHALLENGE_TYPE_SUCCESS = 'ADD_CHALLENGE_TYPE_SUCCESS';
export const ADD_CHALLENGE_TYPE_FAILED = 'ADD_CHALLENGE_TYPE_FAILED';