export const GET_CHALLENGES_STATE_FAILED = 'GET_CHALLENGES_STATE_FAILED';
export const GET_CHALLENGES_STATE_SUCCESS = 'GET_CHALLENGES_STATE_SUCCESS';
export const GET_CHALLENGES_STATE_LOADING = 'GET_CHALLENGES_STATE_LOADING';
export const ADD_CHALLENGE_LOADING = 'ADD_CHALLENGE_LOADING';
export const ADD_CHALLENGE_SUCCESS = 'ADD_CHALLENGE_SUCCESS';
export const ADD_CHALLENGE_FAILED = 'ADD_CHALLENGE_FAILED';